[project]
name = "csv-to-json"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mypy>=1.16.0",
    "pandas>=2.2.3",
    "pylint>=3.3.7",
    "rich>=14.0.0",
    "ruff>=0.11.12",
]
